/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChannelId = string;
export interface ChannelRecord {
  'id' : ChannelId,
  'status' : ChannelStatus,
  'lockedA' : bigint,
  'lockedB' : bigint,
  'partyA' : LxmfHash,
  'partyB' : LxmfHash,
}
export type ChannelStatus = { 'Open' : null } |
  { 'Closed' : null };
export type EventLogEntry = string;
export type HtlcId = string;
export interface HtlcRecord {
  'id' : HtlcId,
  'status' : HtlcStatus,
  'senderLxmfHash' : LxmfHash,
  'receiverLxmfHash' : LxmfHash,
  'paymentHash' : string,
  'expiry' : Timestamp,
  'amount' : bigint,
}
export type HtlcStatus = { 'Refunded' : null } |
  { 'Released' : null } |
  { 'Locked' : null };
export type LxmfHash = string;
export type Timestamp = bigint;
export interface _SERVICE {
  '__balances' : ActorMethod<[], any>,
  '__channels' : ActorMethod<[], any>,
  '__eventLog' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<EventLogEntry>
  >,
  '__htlcs' : ActorMethod<[], any>,
  '__nextChannelId' : ActorMethod<[], any>,
  '__nextHtlcId' : ActorMethod<[], any>,
  '__nonces' : ActorMethod<[], any>,
  '__publicKeys' : ActorMethod<[], any>,
  'closeChannelCooperative' : ActorMethod<
    [ChannelId, bigint, bigint, bigint, bigint, string, string],
    undefined
  >,
  'deposit' : ActorMethod<[LxmfHash, bigint], undefined>,
  'getBalance' : ActorMethod<[LxmfHash], bigint>,
  'getChannel' : ActorMethod<[ChannelId], [] | [ChannelRecord]>,
  'getHTLC' : ActorMethod<[HtlcId], [] | [HtlcRecord]>,
  'getNonce' : ActorMethod<[LxmfHash], bigint>,
  'getRegisteredPublicKey' : ActorMethod<[LxmfHash], [] | [string]>,
  'joinChannel' : ActorMethod<
    [ChannelId, LxmfHash, bigint, bigint, string],
    undefined
  >,
  'listChannelsForAddress' : ActorMethod<[LxmfHash], Array<ChannelRecord>>,
  'listHTLCsForAddress' : ActorMethod<[LxmfHash], Array<HtlcRecord>>,
  'lockHTLC' : ActorMethod<
    [LxmfHash, LxmfHash, bigint, string, bigint, bigint, string],
    HtlcId
  >,
  'openChannel' : ActorMethod<
    [LxmfHash, LxmfHash, bigint, bigint, string],
    ChannelId
  >,
  'refundHTLC' : ActorMethod<[HtlcId], undefined>,
  'registerPublicKey' : ActorMethod<[LxmfHash, string], undefined>,
  'releaseHTLC' : ActorMethod<[HtlcId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];