/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EventLogEntry = IDL.Text;
export const LxmfHash = IDL.Text;
export const HtlcId = IDL.Text;
export const HtlcStatus = IDL.Variant({
  'Refunded' : IDL.Null,
  'Released' : IDL.Null,
  'Locked' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const HtlcRecord = IDL.Record({
  'id' : HtlcId,
  'status' : HtlcStatus,
  'senderLxmfHash' : LxmfHash,
  'receiverLxmfHash' : LxmfHash,
  'paymentHash' : IDL.Text,
  'expiry' : Timestamp,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '__balances' : IDL.Func([], [IDL.Reserved], ['query']),
  '__eventLog' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(EventLogEntry)],
      ['query'],
    ),
  '__htlcs' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextHtlcId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__publicKeys' : IDL.Func([], [IDL.Reserved], ['query']),
  'deposit' : IDL.Func([LxmfHash, IDL.Nat], [], []),
  'getBalance' : IDL.Func([LxmfHash], [IDL.Nat], ['query']),
  'getHTLC' : IDL.Func([HtlcId], [IDL.Opt(HtlcRecord)], ['query']),
  'getRegisteredPublicKey' : IDL.Func(
      [LxmfHash],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'listHTLCsForAddress' : IDL.Func(
      [LxmfHash],
      [IDL.Vec(HtlcRecord)],
      ['query'],
    ),
  'lockHTLC' : IDL.Func(
      [LxmfHash, LxmfHash, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [HtlcId],
      [],
    ),
  'refundHTLC' : IDL.Func([HtlcId], [], []),
  'registerPublicKey' : IDL.Func([LxmfHash, IDL.Text], [], []),
  'releaseHTLC' : IDL.Func([HtlcId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EventLogEntry = IDL.Text;
  const LxmfHash = IDL.Text;
  const HtlcId = IDL.Text;
  const HtlcStatus = IDL.Variant({
    'Refunded' : IDL.Null,
    'Released' : IDL.Null,
    'Locked' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const HtlcRecord = IDL.Record({
    'id' : HtlcId,
    'status' : HtlcStatus,
    'senderLxmfHash' : LxmfHash,
    'receiverLxmfHash' : LxmfHash,
    'paymentHash' : IDL.Text,
    'expiry' : Timestamp,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '__balances' : IDL.Func([], [IDL.Reserved], ['query']),
    '__eventLog' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(EventLogEntry)],
        ['query'],
      ),
    '__htlcs' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextHtlcId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__publicKeys' : IDL.Func([], [IDL.Reserved], ['query']),
    'deposit' : IDL.Func([LxmfHash, IDL.Nat], [], []),
    'getBalance' : IDL.Func([LxmfHash], [IDL.Nat], ['query']),
    'getHTLC' : IDL.Func([HtlcId], [IDL.Opt(HtlcRecord)], ['query']),
    'getRegisteredPublicKey' : IDL.Func(
        [LxmfHash],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'listHTLCsForAddress' : IDL.Func(
        [LxmfHash],
        [IDL.Vec(HtlcRecord)],
        ['query'],
      ),
    'lockHTLC' : IDL.Func(
        [LxmfHash, LxmfHash, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [HtlcId],
        [],
      ),
    'refundHTLC' : IDL.Func([HtlcId], [], []),
    'registerPublicKey' : IDL.Func([LxmfHash, IDL.Text], [], []),
    'releaseHTLC' : IDL.Func([HtlcId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };