/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface HtlcRecord {
    id: HtlcId;
    status: HtlcStatus;
    senderLxmfHash: LxmfHash;
    receiverLxmfHash: LxmfHash;
    paymentHash: string;
    expiry: Timestamp;
    amount: bigint;
}
export type ChannelId = string;
export type HtlcId = string;
export interface ChannelRecord {
    id: ChannelId;
    status: ChannelStatus;
    lockedA: bigint;
    lockedB: bigint;
    partyA: LxmfHash;
    partyB: LxmfHash;
}
export type LxmfHash = string;
export type EventLogEntry = string;
export enum ChannelStatus {
    Open = "Open",
    Closed = "Closed"
}
export enum HtlcStatus {
    Refunded = "Refunded",
    Released = "Released",
    Locked = "Locked"
}
export interface backendInterface {
    __balances(): Promise<any>;
    __channels(): Promise<any>;
    __eventLog(io: bigint | null, count: bigint | null): Promise<Array<EventLogEntry>>;
    __htlcs(): Promise<any>;
    __nextChannelId(): Promise<any>;
    __nextHtlcId(): Promise<any>;
    __publicKeys(): Promise<any>;
    closeChannelCooperative(channelId: ChannelId, finalBalanceA: bigint, finalBalanceB: bigint, sigA: string, sigB: string): Promise<void>;
    deposit(lxmfHash: LxmfHash, amount: bigint): Promise<void>;
    getBalance(lxmfHash: LxmfHash): Promise<bigint>;
    getChannel(channelId: ChannelId): Promise<ChannelRecord | null>;
    getHTLC(htlcId: HtlcId): Promise<HtlcRecord | null>;
    getRegisteredPublicKey(lxmfHash: LxmfHash): Promise<string | null>;
    joinChannel(channelId: ChannelId, partyB: LxmfHash, amountB: bigint, signature: string): Promise<void>;
    listChannelsForAddress(lxmfHash: LxmfHash): Promise<Array<ChannelRecord>>;
    listHTLCsForAddress(lxmfHash: LxmfHash): Promise<Array<HtlcRecord>>;
    lockHTLC(senderLxmfHash: LxmfHash, receiverLxmfHash: LxmfHash, amount: bigint, paymentHash: string, expirySeconds: bigint, signature: string): Promise<HtlcId>;
    openChannel(partyA: LxmfHash, partyB: LxmfHash, amountA: bigint, signature: string): Promise<ChannelId>;
    refundHTLC(htlcId: HtlcId): Promise<void>;
    registerPublicKey(lxmfHash: LxmfHash, publicKeyHex: string): Promise<void>;
    releaseHTLC(htlcId: HtlcId, preimage: string): Promise<void>;
}
import type { ChannelId as _ChannelId, ChannelRecord as _ChannelRecord, ChannelStatus as _ChannelStatus, HtlcId as _HtlcId, HtlcRecord as _HtlcRecord, HtlcStatus as _HtlcStatus, LxmfHash as _LxmfHash, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __balances(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__balances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__balances();
            return result;
        }
    }
    async __channels(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__channels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__channels();
            return result;
        }
    }
    async __eventLog(arg0: bigint | null, arg1: bigint | null): Promise<Array<EventLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.__eventLog(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__eventLog(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __htlcs(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__htlcs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__htlcs();
            return result;
        }
    }
    async __nextChannelId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextChannelId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextChannelId();
            return result;
        }
    }
    async __nextHtlcId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextHtlcId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextHtlcId();
            return result;
        }
    }
    async __publicKeys(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__publicKeys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__publicKeys();
            return result;
        }
    }
    async closeChannelCooperative(arg0: ChannelId, arg1: bigint, arg2: bigint, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeChannelCooperative(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeChannelCooperative(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deposit(arg0: LxmfHash, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deposit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deposit(arg0, arg1);
            return result;
        }
    }
    async getBalance(arg0: LxmfHash): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance(arg0);
            return result;
        }
    }
    async getChannel(arg0: ChannelId): Promise<ChannelRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannel(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannel(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHTLC(arg0: HtlcId): Promise<HtlcRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHTLC(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHTLC(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegisteredPublicKey(arg0: LxmfHash): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegisteredPublicKey(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegisteredPublicKey(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinChannel(arg0: ChannelId, arg1: LxmfHash, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinChannel(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinChannel(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async listChannelsForAddress(arg0: LxmfHash): Promise<Array<ChannelRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChannelsForAddress(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChannelsForAddress(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listHTLCsForAddress(arg0: LxmfHash): Promise<Array<HtlcRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHTLCsForAddress(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHTLCsForAddress(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async lockHTLC(arg0: LxmfHash, arg1: LxmfHash, arg2: bigint, arg3: string, arg4: bigint, arg5: string): Promise<HtlcId> {
        if (this.processError) {
            try {
                const result = await this.actor.lockHTLC(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockHTLC(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async openChannel(arg0: LxmfHash, arg1: LxmfHash, arg2: bigint, arg3: string): Promise<ChannelId> {
        if (this.processError) {
            try {
                const result = await this.actor.openChannel(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.openChannel(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async refundHTLC(arg0: HtlcId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.refundHTLC(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refundHTLC(arg0);
            return result;
        }
    }
    async registerPublicKey(arg0: LxmfHash, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPublicKey(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPublicKey(arg0, arg1);
            return result;
        }
    }
    async releaseHTLC(arg0: HtlcId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.releaseHTLC(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.releaseHTLC(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ChannelRecord_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChannelRecord): ChannelRecord {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ChannelStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChannelStatus): ChannelStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_HtlcRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HtlcRecord): HtlcRecord {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_HtlcStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HtlcStatus): HtlcStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChannelRecord]): ChannelRecord | null {
    return value.length === 0 ? null : from_candid_ChannelRecord_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HtlcRecord]): HtlcRecord | null {
    return value.length === 0 ? null : from_candid_HtlcRecord_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ChannelId;
    status: _ChannelStatus;
    lockedA: bigint;
    lockedB: bigint;
    partyA: _LxmfHash;
    partyB: _LxmfHash;
}): {
    id: ChannelId;
    status: ChannelStatus;
    lockedA: bigint;
    lockedB: bigint;
    partyA: LxmfHash;
    partyB: LxmfHash;
} {
    return {
        id: value.id,
        status: from_candid_ChannelStatus_n5(_uploadFile, _downloadFile, value.status),
        lockedA: value.lockedA,
        lockedB: value.lockedB,
        partyA: value.partyA,
        partyB: value.partyB
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _HtlcId;
    status: _HtlcStatus;
    senderLxmfHash: _LxmfHash;
    receiverLxmfHash: _LxmfHash;
    paymentHash: string;
    expiry: _Timestamp;
    amount: bigint;
}): {
    id: HtlcId;
    status: HtlcStatus;
    senderLxmfHash: LxmfHash;
    receiverLxmfHash: LxmfHash;
    paymentHash: string;
    expiry: Timestamp;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_HtlcStatus_n10(_uploadFile, _downloadFile, value.status),
        senderLxmfHash: value.senderLxmfHash,
        receiverLxmfHash: value.receiverLxmfHash,
        paymentHash: value.paymentHash,
        expiry: value.expiry,
        amount: value.amount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Refunded: null;
} | {
    Released: null;
} | {
    Locked: null;
}): HtlcStatus {
    return "Refunded" in value ? HtlcStatus.Refunded : "Released" in value ? HtlcStatus.Released : "Locked" in value ? HtlcStatus.Locked : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Open: null;
} | {
    Closed: null;
}): ChannelStatus {
    return "Open" in value ? ChannelStatus.Open : "Closed" in value ? ChannelStatus.Closed : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChannelRecord>): Array<ChannelRecord> {
    return value.map((x)=>from_candid_ChannelRecord_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HtlcRecord>): Array<HtlcRecord> {
    return value.map((x)=>from_candid_HtlcRecord_n8(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
